<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5qGI5L6L');
$cfg_Cs[2]=array(1,1,1,'572R6aG1');
$cfg_Cs[3]=array(1,1,1,'56e75Yqo5a6i5oi356uv');
$cfg_Cs[4]=array(1,1,1,'5Zu+5qCH5Y+K5bmz6Z2i');
$cfg_Cs[5]=array(0,1,1,'5pyN5Yqh');
$cfg_Cs[6]=array(0,1,1,'5YWz5LqO');
$cfg_Cs[7]=array(0,1,1,'5Yqo5oCB');
$cfg_Cs[8]=array(7,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[9]=array(7,1,1,'5bu656uZ5omL5YaM');
$cfg_Cs[10]=array(7,1,1,'6K6+6K6h5a6d5YW4');
$cfg_Cs[11]=array(7,1,1,'5o6o5bm/56eY57GN');
$cfg_Cs[12]=array(0,1,1,'6IGU57O7');
$cfg_Cs[13]=array(0,1,1,'5a6i5oi3');
?>